# 服务端口
server:
  port: 8201
# 服务名
spring:
  application:
    name: service-hosp
# 环境设置：dev test prod
  profiles:
    active: dev
# MySQL数据库链接
  datasource:
    url: jdbc:mysql://47.94.220.33:3306/yygh_hosp?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
# 返回 JSON的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # mongodb链接信息
  data:
    mongodb:
      uri: mongodb://47.94.220.33:27017/test
# mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    timeout: 1800000